[tool.isort]
profile = "black"

# pyproject.toml
[tool.pytest]
testpaths = ["tests"]

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]


